// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Ce4icIFAD9LdzfiL-cggeoEofUXao4k',
    appId: '1:1016933907693:web:6121bbe0ca0f5b3fe1a0e4',
    messagingSenderId: '1016933907693',
    projectId: 'fir-chat-38490',
    authDomain: 'fir-chat-38490.firebaseapp.com',
    storageBucket: 'fir-chat-38490.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3H6otXgJSnUSvJqj0yPXl2d5Vgydl2tI',
    appId: '1:1016933907693:android:b15999d2441c8b0ae1a0e4',
    messagingSenderId: '1016933907693',
    projectId: 'fir-chat-38490',
    storageBucket: 'fir-chat-38490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmLZNHGq4LYoemmCVc8DjHL5vps8gRTm4',
    appId: '1:1016933907693:ios:265a70014006c832e1a0e4',
    messagingSenderId: '1016933907693',
    projectId: 'fir-chat-38490',
    storageBucket: 'fir-chat-38490.appspot.com',
    iosClientId: '1016933907693-1hb8423eq416223tmkqt6j8kvs4k0kmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmLZNHGq4LYoemmCVc8DjHL5vps8gRTm4',
    appId: '1:1016933907693:ios:dccef27d63306826e1a0e4',
    messagingSenderId: '1016933907693',
    projectId: 'fir-chat-38490',
    storageBucket: 'fir-chat-38490.appspot.com',
    iosClientId: '1016933907693-lodch04cghjd7d1sr02f266qkj8h53a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth.RunnerTests',
  );
}
